### ISSUE TITLE
Non-existent service "Divante\NotificationsBundle\Installer"

### ISSUE THREAD

**Issue by kubaplas** [DivanteLtd/pimcore5-notifications#3]
After clicking "enable" in Extensions panel I get an error:
> Timestamp: Tue Oct 17 2017 16:37:25 GMT+0200 (CEST)
> Status: 500 | Internal Server Error
> URL: /admin/extensionmanager/admin/extensions?_dc=1508251043848
> Method: GET
> Message: You have requested a non-existent service "Divante\NotificationsBundle\Installer".

**Comment by kkirsz** [comment]
Probably the problem were solved. Currently I don't use container in the bundle class while instantiating Installer. You can see v1.0.0.3 release.
